name: Docker test and publish

on:
  push:
    branches:
      - main
      - my_testing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: gem install bundler
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Set custom latest version
        if: endsWith(github.ref, '/6.4.x')
        run: echo "::set-env name=LATEST_VERSION::6.4"
      - name: Build container
        working-directory: docker
        run: |
          docker system prune --all --force --volumes
          docker builder prune --force --keep-storage=10GB
      - name: Publish container
        working-directory: docker
        run: |
          make publish
          
